// data/components/badge/2/example.vue
<template>
    <div className="bg-transparent text-white border border-white font-semibold p-1 rounded-md select-none">Badge</div>
        
    <div className="bg-transparent text-[#2E7D32] border border-[#2E7D32] font-semibold p-1 rounded-md select-none">Badge</div>
        
    <div className="bg-transparent text-pink-500 border border-pink-500 font-semibold p-1 rounded-md select-none">Badge</div>
</template>
  
<script>
  export default {
    name: "Badges"
  };
</script>

// data/components/badge/1/example.jsx
const Badges = () => {
    return (
        <>
        
        <div className="bg-white text-black rounded-md p-1 select-none font-semibold">Badge</div>

        <div className="bg-[#2E7D32] text-white rounded-md p-1 select-none font-semibold">Badge</div>
        
        <div className="bg-pink-500 text-white rounded-md p-1 select-none font-semibold">Badge</div>

        </>
    )
}

export default Badges;
