// data/components/badge/1/example.vue
<template>
    <div>
      <div class="bg-white text-black rounded-md p-1 select-none font-semibold">Badge</div>
      <div class="bg-[#2E7D32] text-white rounded-md p-1 select-none font-semibold">Badge</div>
      <div class="bg-pink-500 text-white rounded-md p-1 select-none font-semibold">Badge</div>
    </div>
</template>
  
<script>
  export default {
    name: "Badges"
  };
</script>

// data/components/badge/1/example.jsx
const Badges = () => {
    return (
        <>
        
        <div className="bg-white text-black rounded-md p-1 select-none font-semibold">Badge</div>

        <div className="bg-[#2E7D32] text-white rounded-md p-1 select-none font-semibold">Badge</div>
        
        <div className="bg-pink-500 text-white rounded-md p-1 select-none font-semibold">Badge</div>

        </>
    )
}

export default Badges;
