// data/components/badge/3/example.vue
<template>
    <div className="relative border-white text-white border p-1 rounded-md select-none">
        <div className="absolute size-3 -right-1 -top-1 p-1 bg-[#D32F2F] rounded-full"></div>
        <span>Badge</span>
    </div>

    <div className="relative border-white text-white border p-1 rounded-md select-none">
        <span className="absolute -right-2 -top-1 p-0.5 bg-[#D32F2F] rounded-full text-[8px] text-white">100+</span>
        <span>Badge</span>
    </div>
</template>
  
<script>
  export default {
    name: "Badges"
  };
</script>

// data/components/badge/1/example.jsx
const Badges = () => {
    return (
        <>
        
        <div className="bg-white text-black rounded-md p-1 select-none font-semibold">Badge</div>

        <div className="bg-[#2E7D32] text-white rounded-md p-1 select-none font-semibold">Badge</div>
        
        <div className="bg-pink-500 text-white rounded-md p-1 select-none font-semibold">Badge</div>

        </>
    )
}

export default Badges;
